api/routes/web.php
Route::resource('anexosBugs','AnexosBugsController')->middleware('verified');
Route::post('anexoBugstore','AnexosBugsController@store')->middleware('verified');
Route::get('anexoBug/{id?}','AnexosBugsController@index')->middleware('verified');
Route::get('anexoBug/delete/{id?}','AnexosBugsController@destroy')->middleware('verified');
Route::get('anexoBug/show/{id?}', 'AnexosBugsController@visualizar');

//crud de cuentas de cobro
Route::resource('cobros','CobrosController')->middleware('verified');
Route::get('cobro/show/{id?}','CobrosController@show')->middleware('verified');
Route::post('cobro/generar','CobrosController@generar')->middleware('verified');
Route::post('cobro/store','CobrosController@store')->middleware('verified');
Route::get('cobro/delete/{id?}','CobrosController@destroy')->middleware('verified');
//Para exportar como pdf
Route::get('imprimir/{id}','CobrosController@imprimir')->middleware('verified')->name('imprimir');
Route::post('usuarioCobro','CobrosController@usuarioCobro')->middleware('verified')->name('usuarioCobro');

Route::get('cobro/enviar','CobrosController@enviar')->middleware('verified')->name('cobros.enviar');
Route::post('cobro/enviar','CobrosController@enviarpdf')->middleware('verified')->name('cobros.enviarpdf');


//crud de Anexos Cuentas de cobro
Route::resource('anexosCobros','AnexosCobrosController')->middleware('verified');
Route::post('anexoCobrostore','AnexosCobrosController@store')->middleware('verified');
Route::get('anexoCobro/{id?}','AnexosCobrosController@index')->middleware('verified');
Route::get('anexoCobro/delete/{id?}','AnexosCobrosController@destroy')->middleware('verified');
Route::get('anexoCobro/show/{id?}', 'AnexosCobrosController@visualizar')->name('descargar');

//crud de dispositivos
Route::get('formulariosinfoDispositivos','formularioinfoDispositivosController@index')->name('formulariosinfoDispositivos')->middleware('verified');
Route::post('formulariosinfoDispositivosstore','formularioinfoDispositivosController@store')->middleware('verified');
Route::get('formulariosinfoDispositivosdelete/{id?}','formularioinfoDispositivosController@delete')->middleware('verified');

//crud de conocimiento en pruebas
Route::get('formulariosinfoPruebas','formularioinfoPruebasController@index')->name('formulariosinfoPruebas')->middleware('verified');
Route::post('formulariosinfoPruebasstore','formularioinfoPruebasController@store')->middleware('verified');
Route::get('formulariosinfoPruebasdelete/{id?}','formularioinfoPruebasController@delete')->middleware('verified');

//funciones para obtener listado de maestros: 
Route::get('/getherramientasxTipo/{id}', 'rutinasInfoPruebasController@getherramientasxTipo')->middleware('verified');
Route::get('/getDispositivosxTipo/{id}', 'rutinasInfoPruebasController@getDispositivosxTipo')->middleware('verified');
Route::get('/getDispositivos', 'rutinasInfoPruebasController@getDispositivos')->middleware('verified');
Route::get('/getMarcas', 'rutinasInfoPruebasController@getMarcas')->middleware('verified');
Route::get('/getModelos', 'rutinasInfoPruebasController@getModelos')->middleware('verified');
Route::get('/getSoxDispxTipo/{id}', 'rutinasInfoPruebasController@getSoxDispxTipo')->middleware('verified');
Route::get('/getNavDispxTipo/{id}', 'rutinasInfoPruebasController@getNavDispxTipo')->middleware('verified');

Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Rutas del módulo de Testers
Route::resource('datosBasicos', 'DatosBasicosController')->middleware('verified');
Route::resource('estudiosFormales', 'EstudioFormalController')->middleware('verified');
Route::resource('estudiosNoFormales', 'EstudioNoFormalController')->middleware('verified');
Route::resource('datosLaborales', 'DatoLaboralController')->middleware('verified');
Route::resource('datosFinancieros', 'DatosFinancierosController')->middleware('verified');
Route::resource('anexos','AnexoController')->middleware('auth');
Route::post('anexos/{anexo}','AnexoController@approve')->middleware('auth')->name('anexos.approve');
Route::get('datos','AnexoController@datos')->middleware('verified')->name('datos');
Route::get('terminosCondiciones','AnexoController@terminosCondiciones')->middleware('verified')->name('terminosCondiciones');

//crud de usuarios
Route::resource('usuarios', 'UsuarioController')->middleware('verified');
Route::post('usuario/store','UsuarioController@store')->middleware('verified');
Route::post('usuario/update','UsuarioController@update')->middleware('verified');
Route::post('usuario/cambiarClave','UsuarioController@cambiarclave')->middleware('verified');
// Route::get('usuario/delete/{id?}','UsuarioController@destroy')->middleware('verified');
// Route::get('usuario/show/{id?}','UsuarioController@show')->middleware('verified');

//Rutas de Admin
Route::resource('clientes', 'ClienteController')->middleware('verified');
Route::post('anexoCliente/delete/{id?}','ClienteController@destroyAnexo')->middleware('auth')->name('borrarAnexoCliente');
Route::get('anexoCliente/show/{id?}', 'ClienteController@visualizar')->name('verAnexoCliente');

//Para buscar selects dinámicos
Route::get('/buscarDepartamento','DatosBasicosController@buscarDepartamento')->middleware('verified');
Route::get('/buscarMunicipio','DatosBasicosController@buscarMunicipio')->middleware('verified');
Route::get('/buscarUniversidad','EstudioFormalController@buscarUniversidad')->middleware('verified');

//Para asignar y quitar puntos puntos
Route::get('/asignarPuntos/{id}','PuntosController@asignarPuntos')->name('asignarPuntos')->middleware('verified');
Route::get('/quitarPuntos/{id}','PuntosController@quitarPuntos')->name('quitarPuntos')->middleware('verified');
Route::get('/puntosAcumulados','PuntosController@puntosAcumulados')->name('puntosAcumulados')->middleware('verified');

//Ruta para dashboard NO salen en primera versión
Route::get('inicioTester','InicioTesterController@index')->name('inicioTester')->middleware('verified');
Route::get('inicioLider','InicioLiderController@index')->name('inicioLider')->middleware('verified');
// Route::get('inicioAdmin','InicioAdminController@index')->name('inicioAdmin');
Route::get('puntosTester/{id}','PuntosController@mostrarPuntos')->name('puntosTester')->middleware('verified');

//Rutas para desactivar usuario
Route::get('/desactivar/{id}','DatosBasicosController@desactivar')->name('desactivar')->middleware('verified');

//Ruta para cambiar contraseña
Route::get('/editarContrasena/{id}','DatosBasicosController@editarContrasena')->name('editarContrasena')->middleware('verified');;
Route::put('/actualizarContrasena/{id}','DatosBasicosController@actualizarContrasena')->name('actualizarContrasena')->middleware('verified');;

//Ruta para anexos de tester

/*Route::get('/', function () {
    return view('home');
});*/
Route::get('/', 'HomeController@homeView');

//Ruta para devolver
Route::get('regresar', 'HomeController@return')->name('regresar');

//Rutas de paginas de inicio
Route::view('/about','about')->name('about');
Route::view('/contact','inicio_crowd.contacto')->name('contacto');
Route::post('contact', 'MessageController@store')->name('mensaje');

//crud de Anexos Proyectos
Route::resource('anexosProyectos','AnexosProyectosController')->middleware('verified');
Route::post('anexoProyectostore','AnexosProyectosController@store')->middleware('verified');
Route::get('anexoProyecto/{id?}','AnexosProyectosController@index')->middleware('verified');
Route::get('anexoProyecto/delete/{id?}','AnexosProyectosController@destroy')->middleware('verified');


//Rutas para el modulo de proyectos

Route::resource('misproyectos', 'MisproyectosController')->middleware('verified');
//correos inicio y fin
Route::get('mail/inicio/{id?}', 'InvitacionController@inicio')->middleware('verified');
Route::get('mail/fin/{id?}', 'InvitacionController@fin')->middleware('verified');

Route::resource('proyectos', 'ProyectosController')->middleware('verified');
Route::post('proyecto/store', 'ProyectosController@store')->middleware('verified');
Route::get('proyecto/delete/{id?}', 'ProyectosController@destroy')->middleware('verified');

Route::Resource('invitacion','InvitacionController')->middleware('verified');

Route::resource('invitaciones', 'InvitacionesController')->middleware('verified');
Route::get('invitaciones/edit/{id?}', 'InvitacionesController@edit')->middleware('verified');
Route::get('invitaciones/delete/{id?}', 'InvitacionesController@destroy')->middleware('verified');

Route::resource('proyectos_responsables', 'proyectos_responsablesController')->middleware('verified');
Route::post('proyectos_responsables/store', 'proyectos_responsablesController@store')->middleware('verified');
Route::get('proyectos_responsables/delete/{id?}', 'proyectos_responsablesController@destroy')->middleware('verified');
Route::get('proyectos_responsables/ver/{id?}', 'proyectos_responsablesController@ver')->middleware('verified');
Route::get('proyectos_responsables/edit/{id?}', 'proyectos_responsablesController@edit')->middleware('verified');

Route::get('proyectos_tester', 'proyectos_testerController@index')->middleware('verified');
Route::post('proyectos_tester/store', 'proyectos_testerController@store')->middleware('verified');
Route::get('proyectos_tester/delete/{id?}', 'proyectos_testerController@destroy')->middleware('verified');
Route::get('proyectos_tester/asignar/{id?}', 'proyectos_testerController@asignar')->middleware('verified');

//consultar si existen bugs en estado 1 o 6 para un tester o proyecto
Route::get('bugsxtester/{id?}','ValidarBugsController@tester')->middleware('verified');
Route::get('bugsxproyecto/{id?}','ValidarBugsController@proyecto')->middleware('verified');

Route::resource('alertas', 'AlertasController')->middleware('verified');
Route::post('alertas/asignarUsuarios', 'AlertasController@asignarUsuarios')->middleware('verified')->name('alertas.usuarios');

api/app/Http/Controllers/Api/DatosFinancierosController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\User;
use App\DatoFinanciero;
use App\Models\TipoBanco;
use App\Models\TipoCuentaBancaria;

use App\Services\crypto;
use Carbon\Carbon;

class DatosFinancierosController extends Controller
{
    public function index(Request $request){
        try {
            $user = $request->user()->id;
            $datosFinancieros = DatoFinanciero::where("user_id","=",$user)->get();
    
            foreach ($datosFinancieros as &$dato) {
                $dato->banco = TipoBanco::find($dato->banco_id);
                $dato->cuentaBancaria = TipoCuentaBancaria::find($dato->cuentaBancaria_id);
            }

            return \Response::json([
                'datosFinancieros' => crypto::arrayEncrypt($datosFinancieros)
            ]);
        } catch (\Throwable $th) {
            return response()->json([ 'error' => $th->getMessage() ]);
        }
    }

    public function crud(Request $request)
    {
        try {
            $datos = $request->only('banco_id','cuentaBancaria_id','numeroCuenta','sucursal');
            $user = User::where('email', $request->user()->email)->first();
            $datos['user_id'] = $user->id;
            $datos['nombreTitular'] = $user->name . " " . $user->lastname;
            $datos['no_retencion_sin_minimo'] = "on";
            $datos['no_personas_vinculadas'] = "on";
            $id = $request->input('id');
            if(isset($id)){
                $datos['updated_at'] = Carbon::now();
                $dispositivo = \DB::table('datos_financieros')
                                ->where('id_datoFinanciero', $id)
                                ->update($datos);
            } else {
                $datos['created_at'] = Carbon::now();
                \DB::table('datos_financieros')->insert($datos);
            }
            return response()->json(['message' => 'ok'], 200);
        } catch (\Throwable $th) {
            return \Response::json(['error' => $th->getMessage()]);
        }
    }

    public function delete($id)
    {
        try {
            \DB::delete("DELETE FROM datos_financieros WHERE id_datoFinanciero = '$id'");
            return \Response::json(['message' => 'ok'], 200);
        } catch (\Throwable $th) {
            return \Response::json(['error' => $th->getMessage()]);
        }
    }
}

api/resources/views/datos_financieros/create.blade.php
@extends('layouts.app2')

@section('content')
<div>
    <h3 class="centrar"> <strong> Añadir información financiera </strong></h3>
</div> <br>

<form method="POST" action="{{ route('datosFinancieros.store') }}">

    @include('flash::message')
    @include('datos_financieros.fields_create')

</form>
@endsection

api/resources/views/datos_financieros/edit.blade.php
@extends('layouts.app2')

@section('content')
<div>
    <h3 class="centrar"> <strong> Editar mi información financiera </strong></h3>
</div> <br>

@foreach($datosFinancieros as $datoFinanciero)
<form action="{{ route('datosFinancieros.update', $datoFinanciero->id_datoFinanciero) }}" method="POST" id="actualizar_datosFinancieros">

    @method('PUT')
    @include('flash::message')
    @include('datos_financieros.fields_edit')

</form>
@endforeach
@endsection

api/resources/views/datos_financieros/fields_create.blade.php
@csrf
@inject('tipoBancos','App\Services\tipoBancos')
@inject('tipoCuentasBancarias','App\Services\tipoCuentasBancarias')

<style>

    .caja {
    font-family: sans-serif;
    font-size: 12px;
    font-weight: 400;
    color: #304457;
    background: #E0F8F7;
    margin: 0 0 25px;
    overflow: hidden;
    padding: 10px;
    }

    /* The container */
    .container1 {
    display: block;
    position: relative;
    padding-left: 35px;
    margin-bottom: 12px;
    cursor: pointer;
    font-size: 12px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    }

    /* Hide the browser's default checkbox */
    .container1 input {
    position: absolute;
    opacity: 0;
    cursor: pointer;
    height: 0;
    width: 0;
    }

    /* Create a custom checkbox */
    .checkmark {
    position: absolute;
    top: 0;
    left: 0;
    height: 20px;
    width: 20px;
    background-color:#E6E6E6;

    }

    /* On mouse-over, add a grey background color */
    .container1:hover input ~ .checkmark {
    background-color: #304457;
    }

    /* When the checkbox is checked, add a blue background */
    .container1 input:checked ~ .checkmark {
    background-color: #304457;
    }

    /* Create the checkmark/indicator (hidden when not checked) */
    .checkmark:after {
    content: "";
    position: absolute;
    display: none;
    }

    /* Show the checkmark when checked */
    .container1 input:checked ~ .checkmark:after {
    display: block;
    }

    /* Style the checkmark/indicator */
    .container1 .checkmark:after {
    left: 9px;
    top: 5px;
    width: 5px;
    height: 10px;
    border: solid white;
    border-width: 0 3px 3px 0;
    -webkit-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    transform: rotate(45deg);
    }

    
</style>

<div class="form-group col-sm-12">

    <div class="form-group col-sm-2"> </div>
    <div class="form-group col-sm-8">

        <div class="caja">
            Solicitamos tu información financiera, con el fin de tenerla disponible en el momento en que se vayan a realizar pagos por tu participación en CROWDSQA. <br><br>Por favor ten presente que tu nombre debe estar registrado, tal cómo aparece en tu documento de identificación. Las condiciones de pago por actividades realizadas en CrowdSQA,están señaladas en nuestros Términos y condiciones, disponibles en la página de registro.  
        </div>

        <!-- Banco -->
        <div class="form-group col-sm-6">
            <label for="banco_id">¿Cuál es tu entidad bancaria?</label>
            <select class="form-control" value="{{old('banco_id')}}" id="banco_id" name="banco_id" required>
                @foreach($tipoBancos->get() as $index => $tipoBancos)
                <option value="{{ $index }}" {{old('banco_id') == $index ? 'selected' : ''}}> {{  $tipoBancos }}
                </option>
                @endforeach
            </select>
            @if ($errors->has('banco_id'))
            <span class="help-block" style="color:#F3A100" ;>
                <small><i>{{ $errors->first('banco_id') }}</i></small>
            </span>
            @endif
        </div>

        <!-- Tipo cuenta bancaria -->
        <div class="form-group col-sm-6">
            <label for="cuentaBancaria_id">¿Que tipo de cuenta bancaria tienes?:</label>
            <select class="form-control" value="{{old('cuentaBancaria_id')}}" id="cuentaBancaria_id"  name="cuentaBancaria_id" required>
                @foreach($tipoCuentasBancarias->get() as $index => $tipoCuentasBancarias)
                <option value="{{ $index }}" {{old('cuentaBancaria_id') == $index ? 'selected' : ''}}>
                    {{  $tipoCuentasBancarias }}</option>
                @endforeach
            </select>
            @if ($errors->has('cuentaBancaria_id'))
            <span class="help-block" style="color:#F3A100" ;>
                <small><i>{{ $errors->first('cuentaBancaria_id') }}</i></small>
            </span>
            @endif
        </div>

        <!-- Número de Cuenta-->
        <div class="form-group col-sm-6">
            <label for="numeroCuenta">¿Cuál es tu número de cuenta?</label>
            <input class="form-control" value="{{old('numeroCuenta')}}" name="numeroCuenta" type="text" id="numeroCuenta" minlength="6" maxlength="15" required pattern="[0-9]{6,15}" title="Tu número de cuenta debe ser un número y contener entre 6 y 15 caracteres">
            @if ($errors->has('numeroCuenta'))
            <span class="help-block" style="color:#F3A100" ;>
                <small><i>{{ $errors->first('numeroCuenta') }}</i></small>
            </span>
            @endif
        </div>

        <!-- Nombre del Titular-->
        <div class="form-group col-sm-6">
            <label for="nombreTitular">¿Cuál es el nombre del titular de la cuenta?</label>
            <input class="form-control" value={{auth()->user()->name}} name="nombreTitular" type="text" id="nombreTitular" required readonly>
            @if ($errors->has('nombreTitular'))
            <span class="help-block" style="color:#F3A100" ;>
                <small><i>{{ $errors->first('nombreTitular') }}</i></small>
            </span>
            @endif
        </div>

        <!-- Sucursal-->
        <div class="form-group col-sm-6">
            <label for="sucursal">¿Cuál es tu sucursal bancaria?</label>
            <input class="form-control" value="{{old('sucursal')}}" name="sucursal" type="text" id="sucursal" minlength="2" maxlength="50" required pattern="[a-zA-Z0-9 ]{2,50}" title="El nombre sólo puede contener letras, números y espacios, y tener entre 2 y 50 caracteres">
            @if ($errors->has('sucursal'))
            <span class="help-block" style="color:#F3A100" ;>
                <small><i>{{ $errors->first('sucursal') }}</i></small>
            </span>
            @endif
        </div>

        <div  class="form-group col-sm-6">
            <label class="container1" for="no_retencion_sin_minimo" style="font-weight: normal"> Solicito no practicar retención en la fuente si la misma no excede el tope mínimo de la tabla de retención del estatuto tributario Colombiano.
                <input type="checkbox"  id="no_retencion_sin_minimo" name="no_retencion_sin_minimo" checked> 
                <span class="checkmark"></span>                
            </label>
                @if ($errors->has('no_retencion_sin_minimo'))
                <span class="help-block" style="color:#F3A100">
                    <small><i>{{ $errors->first('no_retencion_sin_minimo') }}</i></small>
                </span>
                @endif
     

            <label class="container1" for="no_personas_vinculadas" style="font-weight: normal"> Declaro no tener vinculados o contratados 2 o más trabajadores asociados a mi actividad
                <input type="checkbox"  id="no_personas_vinculadas" name="no_personas_vinculadas" checked > 
                <span class="checkmark"></span> 
            </label>
            @if ($errors->has('no_personas_vinculadas'))
            <span class="help-block" style="color:#F3A100" >
                <small><i>{{ $errors->first('no_personas_vinculadas') }}</i></small>
            </span>
            @endif
        </div>


        <!-- UserID Field -->
        <div class="form-group col-sm-6">
        	<label for="user_id"> </label>
            <input class="form-control" name="user_id" type="hidden" value={{auth()->user()->id}} readonly="readonly">
        </div>

        <!-- Submit Field -->
        <div class="form-group col-sm-12">
        <center><label>*Todos los campos son obligatorios</label></center><br><br>
            <div class="centrar">
                <input class="btn btn-primary" type="submit" value="Guardar">
                <a href={{ route('datosFinancieros.index') }} class="btn btn-default">Cancelar</a>
            </div>
        </div>

    </div>
</div>
<div class="form-group col-sm-2"></div>
</div>

api/resources/views/datos_financieros/fields_show.blade.php
<!-- Banco -->
<div class="form-group">
    <label for="banco_id">¿Cuál es tu entidad bancaria?</label>
    <p>{{ $datoFinanciero->tipoBanco->nombre_banco }}</p>
</div>

<!-- Cuenta Bancaria -->
<div class="form-group">
    <label for="cuentaBancaria_id">¿Que tipo de cuenta bancaria tienes?:</label>
    <p>{{ $datoFinanciero->tipoCuentaBancaria->nombre_cuentaBancaria }}</p>
</div>

<!-- Numero de cuenta -->
<div class="form-group">
    <label for="numeroCuenta">¿Cuál es el nombre del titular de la cuenta?</label>
    <p>{{ $datoFinanciero->numeroCuenta }}</p>
</div>

<!-- Nombre del titular -->
<div class="form-group">
    <label for="nombreTitular">¿Cuál es el nombre del titular de la cuenta?</label>
    <p>{{ $datoFinanciero->nombreTitular }}</p>
</div>

<!-- Sucursal -->
<div class="form-group">
    <label for="sucursal">¿Cuál es tu sucursal bancaria?</label>
    <p>{{ $datoFinanciero->sucursal }}</p>
</div>

api/resources/views/datos_financieros/index.blade.php
@extends('layouts.app2')

@section('content')

@if ($datosFinancieros->isEmpty())
<h1 class="pull-right">
    <a class="btn btn-default btn-xs pull-right" style="margin-top: -10px;margin-bottom: 5px; margin: 10px"
        href="{{ route('datosFinancieros.create') }}">Añadir información financiera</a>
</h1>
<br>
    <br>
    <br>
    <br>
    <br>
<div style="text-align:center">
    <h3 >Aún no has agregado tus datos financieros</h3>
	<h5>
		Recuerda que esta sección de tu perfil es obligatoria para quedar activo en la plataforma.
	</h5>
</div>
@else
    <h3  style="text-align:center"> Información Financiera </h3>
    @include('flash::message')
    @include('datos_financieros.table')
@endif
    @endsection

api/resources/views/datos_financieros/show.blade.php
@extends('layouts.tester')

@section('content')
    <section class="content-header">
        <h1>
            Mi información Financiera
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    
                    @foreach($datosFinancieros as $datoFinanciero)
                    @include('datos_financieros.fields_show')
                    @endforeach
                    <a href="{{ route('datosFinancieros.index') }}" class="btn btn-default">Volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

api/resources/views/datos_financieros/table.blade.php
<div class="container.fluid py-0 px-1">
    <div class="row">
        <div class="col-sm col-1 col-lg-1">
        </div>
        <div class="col-sm col-12 col-lg-12">
            <div class="table-responsive">
                <table class="table" id="datosFinancieros-table">
                    <thead>
                        <tr>
                            <th>Entidad Bancaria</th>
                            <th>Tipo de Cuenta</th>
                            <th>Número de Cuenta</th>
                            <th>Nombre del Titular</th>
                            <th>Sucursal</th>
                            <th colspan="3">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($datosFinancieros as $datoFinanciero)
                        <tr>
                            <td>{{ $datoFinanciero->tipoBanco->nombre_banco }}</td>
                            <td>{{ $datoFinanciero->tipoCuentaBancaria->nombre_cuentaBancaria}}</td>
                            <td>{{ $datoFinanciero->numeroCuenta}}</td>
                            <td>{{ $datoFinanciero->nombreTitular }}</td>
                            <td>{{ $datoFinanciero->sucursal }}</td>
                            <td>

                                <form
                                    action="{{ route('datosFinancieros.destroy',$datoFinanciero->id_datoFinanciero) }}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')

                                    <div class='pull right'>
                                        <a href="{{ route('datosFinancieros.edit',$datoFinanciero->id_datoFinanciero) }}"
                                            class="btn btn-default btn-xs" style="margin-bottom: 5px;"> <i class="lnr lnr-pencil"></i></a>
                                        <button type="submit" class="btn btn-danger btn-xs" style="margin-bottom: 5px" 
                                            onclick="return confirm('¿Estás seguro?')"> <i class="lnr lnr-cross"></i> </button>
                                    </div>
                                </form>

                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="pull-right">
                    <small>{{ $datosFinancieros->links() }}</small>
                </div>
            
            </div>
        </div>
        <div class="col-sm col-1 col-lg-1">
        </div>
    </div>
</div>