api/routes/web.php
Route::resource('anexosBugs','AnexosBugsController')->middleware('verified');
Route::post('anexoBugstore','AnexosBugsController@store')->middleware('verified');
Route::get('anexoBug/{id?}','AnexosBugsController@index')->middleware('verified');
Route::get('anexoBug/delete/{id?}','AnexosBugsController@destroy')->middleware('verified');
Route::get('anexoBug/show/{id?}', 'AnexosBugsController@visualizar');

//crud de cuentas de cobro
Route::resource('cobros','CobrosController')->middleware('verified');
Route::get('cobro/show/{id?}','CobrosController@show')->middleware('verified');
Route::post('cobro/generar','CobrosController@generar')->middleware('verified');
Route::post('cobro/store','CobrosController@store')->middleware('verified');
Route::get('cobro/delete/{id?}','CobrosController@destroy')->middleware('verified');
//Para exportar como pdf
Route::get('imprimir/{id}','CobrosController@imprimir')->middleware('verified')->name('imprimir');
Route::post('usuarioCobro','CobrosController@usuarioCobro')->middleware('verified')->name('usuarioCobro');

Route::get('cobro/enviar','CobrosController@enviar')->middleware('verified')->name('cobros.enviar');
Route::post('cobro/enviar','CobrosController@enviarpdf')->middleware('verified')->name('cobros.enviarpdf');


//crud de Anexos Cuentas de cobro
Route::resource('anexosCobros','AnexosCobrosController')->middleware('verified');
Route::post('anexoCobrostore','AnexosCobrosController@store')->middleware('verified');
Route::get('anexoCobro/{id?}','AnexosCobrosController@index')->middleware('verified');
Route::get('anexoCobro/delete/{id?}','AnexosCobrosController@destroy')->middleware('verified');
Route::get('anexoCobro/show/{id?}', 'AnexosCobrosController@visualizar')->name('descargar');

//crud de dispositivos
Route::get('formulariosinfoDispositivos','formularioinfoDispositivosController@index')->name('formulariosinfoDispositivos')->middleware('verified');
Route::post('formulariosinfoDispositivosstore','formularioinfoDispositivosController@store')->middleware('verified');
Route::get('formulariosinfoDispositivosdelete/{id?}','formularioinfoDispositivosController@delete')->middleware('verified');

//crud de conocimiento en pruebas
Route::get('formulariosinfoPruebas','formularioinfoPruebasController@index')->name('formulariosinfoPruebas')->middleware('verified');
Route::post('formulariosinfoPruebasstore','formularioinfoPruebasController@store')->middleware('verified');
Route::get('formulariosinfoPruebasdelete/{id?}','formularioinfoPruebasController@delete')->middleware('verified');

//funciones para obtener listado de maestros: 
Route::get('/getherramientasxTipo/{id}', 'rutinasInfoPruebasController@getherramientasxTipo')->middleware('verified');
Route::get('/getDispositivosxTipo/{id}', 'rutinasInfoPruebasController@getDispositivosxTipo')->middleware('verified');
Route::get('/getDispositivos', 'rutinasInfoPruebasController@getDispositivos')->middleware('verified');
Route::get('/getMarcas', 'rutinasInfoPruebasController@getMarcas')->middleware('verified');
Route::get('/getModelos', 'rutinasInfoPruebasController@getModelos')->middleware('verified');
Route::get('/getSoxDispxTipo/{id}', 'rutinasInfoPruebasController@getSoxDispxTipo')->middleware('verified');
Route::get('/getNavDispxTipo/{id}', 'rutinasInfoPruebasController@getNavDispxTipo')->middleware('verified');

Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Rutas del módulo de Testers
Route::resource('datosBasicos', 'DatosBasicosController')->middleware('verified');
Route::resource('estudiosFormales', 'EstudioFormalController')->middleware('verified');
Route::resource('estudiosNoFormales', 'EstudioNoFormalController')->middleware('verified');
Route::resource('datosLaborales', 'DatoLaboralController')->middleware('verified');
Route::resource('datosFinancieros', 'DatosFinancierosController')->middleware('verified');
Route::resource('anexos','AnexoController')->middleware('auth');
Route::post('anexos/{anexo}','AnexoController@approve')->middleware('auth')->name('anexos.approve');
Route::get('datos','AnexoController@datos')->middleware('verified')->name('datos');
Route::get('terminosCondiciones','AnexoController@terminosCondiciones')->middleware('verified')->name('terminosCondiciones');

//crud de usuarios
Route::resource('usuarios', 'UsuarioController')->middleware('verified');
Route::post('usuario/store','UsuarioController@store')->middleware('verified');
Route::post('usuario/update','UsuarioController@update')->middleware('verified');
Route::post('usuario/cambiarClave','UsuarioController@cambiarclave')->middleware('verified');
// Route::get('usuario/delete/{id?}','UsuarioController@destroy')->middleware('verified');
// Route::get('usuario/show/{id?}','UsuarioController@show')->middleware('verified');

//Rutas de Admin
Route::resource('clientes', 'ClienteController')->middleware('verified');
Route::post('anexoCliente/delete/{id?}','ClienteController@destroyAnexo')->middleware('auth')->name('borrarAnexoCliente');
Route::get('anexoCliente/show/{id?}', 'ClienteController@visualizar')->name('verAnexoCliente');

//Para buscar selects dinámicos
Route::get('/buscarDepartamento','DatosBasicosController@buscarDepartamento')->middleware('verified');
Route::get('/buscarMunicipio','DatosBasicosController@buscarMunicipio')->middleware('verified');
Route::get('/buscarUniversidad','EstudioFormalController@buscarUniversidad')->middleware('verified');

//Para asignar y quitar puntos puntos
Route::get('/asignarPuntos/{id}','PuntosController@asignarPuntos')->name('asignarPuntos')->middleware('verified');
Route::get('/quitarPuntos/{id}','PuntosController@quitarPuntos')->name('quitarPuntos')->middleware('verified');
Route::get('/puntosAcumulados','PuntosController@puntosAcumulados')->name('puntosAcumulados')->middleware('verified');

//Ruta para dashboard NO salen en primera versión
Route::get('inicioTester','InicioTesterController@index')->name('inicioTester')->middleware('verified');
Route::get('inicioLider','InicioLiderController@index')->name('inicioLider')->middleware('verified');
// Route::get('inicioAdmin','InicioAdminController@index')->name('inicioAdmin');
Route::get('puntosTester/{id}','PuntosController@mostrarPuntos')->name('puntosTester')->middleware('verified');

//Rutas para desactivar usuario
Route::get('/desactivar/{id}','DatosBasicosController@desactivar')->name('desactivar')->middleware('verified');

//Ruta para cambiar contraseña
Route::get('/editarContrasena/{id}','DatosBasicosController@editarContrasena')->name('editarContrasena')->middleware('verified');;
Route::put('/actualizarContrasena/{id}','DatosBasicosController@actualizarContrasena')->name('actualizarContrasena')->middleware('verified');;

//Ruta para anexos de tester

/*Route::get('/', function () {
    return view('home');
});*/
Route::get('/', 'HomeController@homeView');

//Ruta para devolver
Route::get('regresar', 'HomeController@return')->name('regresar');

//Rutas de paginas de inicio
Route::view('/about','about')->name('about');
Route::view('/contact','inicio_crowd.contacto')->name('contacto');
Route::post('contact', 'MessageController@store')->name('mensaje');

//crud de Anexos Proyectos
Route::resource('anexosProyectos','AnexosProyectosController')->middleware('verified');
Route::post('anexoProyectostore','AnexosProyectosController@store')->middleware('verified');
Route::get('anexoProyecto/{id?}','AnexosProyectosController@index')->middleware('verified');
Route::get('anexoProyecto/delete/{id?}','AnexosProyectosController@destroy')->middleware('verified');


//Rutas para el modulo de proyectos

Route::resource('misproyectos', 'MisproyectosController')->middleware('verified');
//correos inicio y fin
Route::get('mail/inicio/{id?}', 'InvitacionController@inicio')->middleware('verified');
Route::get('mail/fin/{id?}', 'InvitacionController@fin')->middleware('verified');

Route::resource('proyectos', 'ProyectosController')->middleware('verified');
Route::post('proyecto/store', 'ProyectosController@store')->middleware('verified');
Route::get('proyecto/delete/{id?}', 'ProyectosController@destroy')->middleware('verified');

Route::Resource('invitacion','InvitacionController')->middleware('verified');

Route::resource('invitaciones', 'InvitacionesController')->middleware('verified');
Route::get('invitaciones/edit/{id?}', 'InvitacionesController@edit')->middleware('verified');
Route::get('invitaciones/delete/{id?}', 'InvitacionesController@destroy')->middleware('verified');

Route::resource('proyectos_responsables', 'proyectos_responsablesController')->middleware('verified');
Route::post('proyectos_responsables/store', 'proyectos_responsablesController@store')->middleware('verified');
Route::get('proyectos_responsables/delete/{id?}', 'proyectos_responsablesController@destroy')->middleware('verified');
Route::get('proyectos_responsables/ver/{id?}', 'proyectos_responsablesController@ver')->middleware('verified');
Route::get('proyectos_responsables/edit/{id?}', 'proyectos_responsablesController@edit')->middleware('verified');

Route::get('proyectos_tester', 'proyectos_testerController@index')->middleware('verified');
Route::post('proyectos_tester/store', 'proyectos_testerController@store')->middleware('verified');
Route::get('proyectos_tester/delete/{id?}', 'proyectos_testerController@destroy')->middleware('verified');
Route::get('proyectos_tester/asignar/{id?}', 'proyectos_testerController@asignar')->middleware('verified');

//consultar si existen bugs en estado 1 o 6 para un tester o proyecto
Route::get('bugsxtester/{id?}','ValidarBugsController@tester')->middleware('verified');
Route::get('bugsxproyecto/{id?}','ValidarBugsController@proyecto')->middleware('verified');

Route::resource('alertas', 'AlertasController')->middleware('verified');
Route::post('alertas/asignarUsuarios', 'AlertasController@asignarUsuarios')->middleware('verified')->name('alertas.usuarios');

api/app/Http/Controllers/AnexosProyectosController.php
<?php
 
namespace App\Http\Controllers;
 
use Illuminate\Http\Request;
use App\Http\Requests\GuardarProyectoAnexoRequest;
use Redirect,Response;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Flash;
 
class AnexosProyectosController extends Controller
{

    public function __construct()
    {        
        $this->middleware([
            'auth','roles:1,2,3']);    
    }
/**
 * Display a listing of the resource.
 *
 * @return \Illuminate\Http\Response
 */
public function index($id)
{  
    //$id = 1;
    $anexos = \DB::table('proyectos_anexos')
                    ->where([
                    ['deleted_at', '=', null],
                    ['proyecto_id', '=', $id],
                    ])
                    ->get();
    
    if(request()->ajax()) {     
      
        return datatables()->of($anexos)
        ->addColumn('action', 'anexos_proyectos.action_button')
        ->rawColumns(['action'])
        ->addIndexColumn()
        ->make(true);   

        return view('anexos_proyectos.index', compact('id'));

    }else{

        return view('anexos_proyectos.index', compact('id'));

    }      
   
    
}
 
 
/**
 * Store a newly created resource in storage.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return \Illuminate\Http\Response
 */
public function store(GuardarProyectoAnexoRequest $request)
{  

    if(auth()->user()->hasRoles(['1','3'])){

        $user_id =  auth()->user()->id;   
        $rol_id = auth()->user()->rol_id;

        $id_proyecto = $request->input('proyecto_id');

        $proyectos = \DB::table('proyectos')->where('id_proyecto', '=',$id_proyecto)->get();
        foreach($proyectos as $proyecto){
            $clienteID = $proyecto->cliente_id;
            $estadoProyecto = $proyecto->ProyectoEstado_id;
            $responsableActual = $proyecto->proyecto_responsable_actual;
        }  

        if($responsableActual === $user_id || $rol_id === 1){

            if($estadoProyecto ===1 || $estadoProyecto ===2){

            $data = $request->validated();

            $files = $request->file('url_anexoProyecto');
            foreach($files as $file){
                
                $nombre      =   time().'.'.$file->getClientOriginalName();
                $target_path    =   storage_path('clientes'.'/cliente_'.$clienteID.'/proyectos'.'/proyecto_'.$id_proyecto.'/anexos'.'/');

                if($file->move($target_path, $nombre)) {
                    $data = array();
                    $data['proyecto_id'] = $id_proyecto;
                    $data['user_id'] = $user_id;
                    $data['url_anexoProyecto'] = $nombre;
                    $data['nota_anexoProyecto'] = $request->input('nota_anexoProyecto');
                    $data['created_at'] = Carbon::now();
                    $data['updated_at'] = Carbon::now();
                    \DB::table('proyectos_anexos')->insert($data);   
                }           
            
            } 
                
            Flash::success('Anexo(s) agregado(s) correctamente');
            return Response::json($data);

            }
        }

        Flash::error('No puede agregar anexos a un proyecto con este estado');
        return Response::json();   

    }

    Flash::error('No está autorizado a agregar anexos a un proyecto');
    return;
                  

}
 
 
/**
 * Show the form for editing the specified resource.
 *
 * @param  \App\Product  $product
 * @return \Illuminate\Http\Response
 */


public function show($id)
{   

    $rol_id = auth()->user()->rol_id;
    $id_user = auth()->user()->id;

    $anexos = \DB::table('proyectos_anexos')->where('id_anexoProyecto', '=',$id)->get();  
    foreach($anexos as $anexo){
        $usuario = $anexo->user_id;
        $url = $anexo->url_anexoProyecto;
        $idProyecto = $anexo->proyecto_id;             
    }

    $clientes = \DB::table('proyectos')->where('id_proyecto', '=',$idProyecto)->get('cliente_id');  
    foreach($clientes as $cliente){
        $clienteID = $cliente->cliente_id;
    }

    if($id_user == $usuario ||$rol_id ==2 ||$rol_id ==1 ){

        $enlace = storage_path('clientes'.'/cliente_'.$clienteID.'/proyectos'.'/proyecto_'.$idProyecto.'/anexos'.'/');
        return response()->download($enlace.$url);

    } else {
        return ('Sólo el propietario puede descargar el archivo');
    }
     
        
}


 
/**
 * Remove the specified resource from storage.
 *
 * @param  \App\Product  $product
 * @return \Illuminate\Http\Response
 */
public function destroy($id)
{
    $user_id = auth()->user()->id;
    $rol_id = auth()->user()->rol_id;

    $anexos = \DB::table('proyectos_anexos')->where('id_anexoProyecto', '=',$id)->get();
    foreach($anexos as $anexo){
             $usuario = $anexo->user_id;
             $url = $anexo->url_anexoProyecto;
             $idProyecto = $anexo->proyecto_id;             
        }

        $clientes = \DB::table('proyectos')->where('id_proyecto', '=',$idProyecto)->get(); 
        
        foreach($clientes as $cliente){
            $clienteID = $cliente->cliente_id;
            $estadoProyecto = $cliente->ProyectoEstado_id;
        }
   
        if (empty($anexos)) {
            return Response::json($anexos);
        }

        if($user_id == $usuario || $rol_id ==1 ){

            if($estadoProyecto !==4 || $estadoProyecto !==3){

                $anexos = \DB::table('proyectos_anexos')->where('id_anexoProyecto', '=',$id)->delete();
                $data = storage_path('clientes'.'/cliente_'.$clienteID.'/proyectos'.'/proyecto_'.$idProyecto.'/anexos'.'/'.$url);
                unlink($data);

                Flash::success('Anexo eliminado correctamente');
                return Response::json($anexos);                
            }               
            

        } else {
                Flash::error('Sólo el propietario puede eliminar el archivo');
                return Response::json(); 
            }

        
    }


}

api/resources/views/anexos_proyectos/action_button.blade.php
@if(auth()->user()->hasRoles(['1','3']))

<a href="{{ route('anexosProyectos.show',$id_anexoProyecto) }}" data-toggle="tooltip"  id="descargar-anexo" data-id="{{ $id_anexoProyecto }}" data-original-title="Edit" 
    class="edit btn btn-default btn-xs " title="Descargar"> <i class="lnr lnr-download"></i></a>

<a href="javascript:void(0);" id="delete-user" data-toggle="tooltip" data-original-title="Delete" 
    data-id="{{ $id_anexoProyecto }}" class="delete btn btn-danger btn-xs" title="Eliminar">  <i class="lnr lnr-cross"></i></a>

@endif


@if(auth()->user()->hasRoles(['2']))

<a href="{{ route('anexosProyectos.show',$id_anexoProyecto) }}" data-toggle="tooltip"  id="descargar-anexo" data-id="{{ $id_anexoProyecto }}" data-original-title="Edit" 
    class="edit btn btn-default btn-xs " title="Descargar"> <i class="lnr lnr-download"></i></a>

@endif

api/resources/views/anexos_proyectos/form.blade.php
<div class="modal fade" id="ajax-crud-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="height:auto; width:600px; padding-right:40px; padding-left:20px; padding-top:20px;">
            <div class="modal-header">
                <h4 class="modal-title" id="anexoCrudModal"></h4>
            </div>
            <div class="modal-body" style="height:400px; width:600px; padding-right:40px; padding-left:40px; padding-top:20px;">
                <form method="POST" enctype="multipart/form-data" id="userForm" name="bugForm" class="form-horizontal">

                    <input type="hidden" name="id_anexoProyecto" id="id_anexoProyecto" value="">

                    
                    <!-- Adjuntos-->
                    <div class="form-group col-sm-12">
                        <label for="url_anexoProyecto" >Agregar anexos al proyecto</label>
                        <small><input type="file" id="url_anexoProyecto" name="url_anexoProyecto[]" accept="image/png, image/jpeg, image/jpg, application/pdf" required title="Este campo es obligatorio, debes adjuntar uno o más archivos" multiple= "multiple"></small>
                        <span class="error"  id="Errorurl_anexoProyecto" style="color:#F3A100" >
                    </div>
                  

                      <!-- Nota-->
                    <div class="form-group col-sm-12">
                        <label for="nota_anexoProyecto">Nota</label>
                        <textarea class="form-control" name="nota_anexoProyecto" value="{{old('nota_anexoProyecto')}}" type="text" id="nota_anexoProyecto" minlength="4" maxlength="100"  title="Este campo es obligatorio, puede contener letras, números y espacios. Y entre 4 y 100 caracteres" > </textarea>
                        <span class="error"  id="Errornota_anexoProyecto" style="color:#F3A100" >
                        <span style="color:#808b96; font-size:10px" id="rchars1" ><small style="color:#808b96; font-size:10px">100</span> caracteres restantes</small>
                    </div>
                  

                    <!-- Submit Field -->
                    <div class="form-group col-sm-12">
                        <div class="centrar">
                            <button type="submit" class="btn btn-primary" id="btn-save" value="create">Guardar cambios
                            </button>
                        </div>
                    </div>

                    <br>
                    <div class="pull-left">
                        <small><i>Sólo se admite archivos con formato pdf, png o jpeg y con un tamaño máximo de 4MB. </i></small>
                    </div> 

                    <!-- ROL ID Field -->
                    <div class="form-group col-sm-6">
                        <label for="rol_id" > </label>
                        <input class="form-control" id="rol_id" type="hidden" name="rol_id"  value={{auth()->user()->rol_id}} readonly >
                    </div>


                    <!-- Proyecto ID Field -->
                    <div class="form-group col-sm-6">
                        <label for="proyecto_id" > </label>
                        <input class="form-control" id="proyecto_id" type="hidden" name="proyecto_id" value="" readonly >
                    </div>


                </form>
            </div>

            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<script>

    var maxLength = 100;
    $('#nota_anexoProyecto').keyup(function() {
    var textlen = maxLength - $(this).val().length;
    $('#rchars1').text(textlen);
    });

</script>

<style>
    .error {
    color: #F3A100;
    font-style: italic;
    font-weight: normal;
    
    }
</style>

<script>


    $(document).on('change','input[type="file"]',function(){
        // this.files[0].size recupera el tamaño del archivo
        // alert(this.files[0].size);
        
        var fileName = this.files[0].name;
        var fileSize = this.files[0].size;

        //aqui el tamaño del archivo se da en terabytes.
        if(fileSize > 4000000){
            alert('El archivo no debe superar los 4MB');
            this.value = '';
            this.files[0].name = '';
        }else{
            // recuperamos la extensión del archivo
            var ext = fileName.split('.').pop();
            
            // Convertimos en minúscula porque 
            // la extensión del archivo puede estar en mayúscula
            ext = ext.toLowerCase();
        
            // console.log(ext);
            switch (ext) {
                case 'jpg':
                case 'jpeg':
                case 'png':
                case 'pdf': break;
                default:
                    alert('El archivo no tiene la extensión adecuada');
                    this.value = ''; // reset del valor
                    this.files[0].name = '';
            }
        }
    });

</script>

<script>

    $(document).ready(function() {
    jQuery.extend(jQuery.validator.messages, {
    required: "Este campo es obligatorio.",
    remote: "Por favor, rellena este campo.",
    email: "Por favor, escribe una dirección de correo válida",
    url: "Por favor, escribe una URL válida.",
    date: "Por favor, escribe una fecha válida.",
    dateISO: "Por favor, escribe una fecha (ISO) válida.",
    number: "Por favor, escribe un número entero válido.",
    digits: "Por favor, escribe sólo dígitos.",
    creditcard: "Por favor, escribe un número de tarjeta válido.",
    equalTo: "Por favor, escribe el mismo valor de nuevo.",
    accept: "Por favor, escribe un valor con una extensión aceptada.",
    maxlength: jQuery.validator.format("Por favor, no escribas más de {0} caracteres."),
    minlength: jQuery.validator.format("Por favor, no escribas menos de {0} caracteres."),
    rangelength: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1} caracteres."),
    range: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1}."),
    max: jQuery.validator.format("Por favor, escribe un valor menor o igual a {0}."),
    min: jQuery.validator.format("Por favor, escribe un valor mayor o igual a {0}.")
    });
    });
</script>

api/resources/views/anexos_proyectos/index.blade.php
@extends('layouts.appAnexos')

@section('content')
        @include('anexos_proyectos.list')
@endsection