api/routes/web.php
Route::resource('anexosBugs','AnexosBugsController')->middleware('verified');
Route::post('anexoBugstore','AnexosBugsController@store')->middleware('verified');
Route::get('anexoBug/{id?}','AnexosBugsController@index')->middleware('verified');
Route::get('anexoBug/delete/{id?}','AnexosBugsController@destroy')->middleware('verified');
Route::get('anexoBug/show/{id?}', 'AnexosBugsController@visualizar');

//crud de cuentas de cobro
Route::resource('cobros','CobrosController')->middleware('verified');
Route::get('cobro/show/{id?}','CobrosController@show')->middleware('verified');
Route::post('cobro/generar','CobrosController@generar')->middleware('verified');
Route::post('cobro/store','CobrosController@store')->middleware('verified');
Route::get('cobro/delete/{id?}','CobrosController@destroy')->middleware('verified');
//Para exportar como pdf
Route::get('imprimir/{id}','CobrosController@imprimir')->middleware('verified')->name('imprimir');
Route::post('usuarioCobro','CobrosController@usuarioCobro')->middleware('verified')->name('usuarioCobro');

Route::get('cobro/enviar','CobrosController@enviar')->middleware('verified')->name('cobros.enviar');
Route::post('cobro/enviar','CobrosController@enviarpdf')->middleware('verified')->name('cobros.enviarpdf');


//crud de Anexos Cuentas de cobro
Route::resource('anexosCobros','AnexosCobrosController')->middleware('verified');
Route::post('anexoCobrostore','AnexosCobrosController@store')->middleware('verified');
Route::get('anexoCobro/{id?}','AnexosCobrosController@index')->middleware('verified');
Route::get('anexoCobro/delete/{id?}','AnexosCobrosController@destroy')->middleware('verified');
Route::get('anexoCobro/show/{id?}', 'AnexosCobrosController@visualizar')->name('descargar');

//crud de dispositivos
Route::get('formulariosinfoDispositivos','formularioinfoDispositivosController@index')->name('formulariosinfoDispositivos')->middleware('verified');
Route::post('formulariosinfoDispositivosstore','formularioinfoDispositivosController@store')->middleware('verified');
Route::get('formulariosinfoDispositivosdelete/{id?}','formularioinfoDispositivosController@delete')->middleware('verified');

//crud de conocimiento en pruebas
Route::get('formulariosinfoPruebas','formularioinfoPruebasController@index')->name('formulariosinfoPruebas')->middleware('verified');
Route::post('formulariosinfoPruebasstore','formularioinfoPruebasController@store')->middleware('verified');
Route::get('formulariosinfoPruebasdelete/{id?}','formularioinfoPruebasController@delete')->middleware('verified');

//funciones para obtener listado de maestros: 
Route::get('/getherramientasxTipo/{id}', 'rutinasInfoPruebasController@getherramientasxTipo')->middleware('verified');
Route::get('/getDispositivosxTipo/{id}', 'rutinasInfoPruebasController@getDispositivosxTipo')->middleware('verified');
Route::get('/getDispositivos', 'rutinasInfoPruebasController@getDispositivos')->middleware('verified');
Route::get('/getMarcas', 'rutinasInfoPruebasController@getMarcas')->middleware('verified');
Route::get('/getModelos', 'rutinasInfoPruebasController@getModelos')->middleware('verified');
Route::get('/getSoxDispxTipo/{id}', 'rutinasInfoPruebasController@getSoxDispxTipo')->middleware('verified');
Route::get('/getNavDispxTipo/{id}', 'rutinasInfoPruebasController@getNavDispxTipo')->middleware('verified');

Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Rutas del módulo de Testers
Route::resource('datosBasicos', 'DatosBasicosController')->middleware('verified');
Route::resource('estudiosFormales', 'EstudioFormalController')->middleware('verified');
Route::resource('estudiosNoFormales', 'EstudioNoFormalController')->middleware('verified');
Route::resource('datosLaborales', 'DatoLaboralController')->middleware('verified');
Route::resource('datosFinancieros', 'DatosFinancierosController')->middleware('verified');
Route::resource('anexos','AnexoController')->middleware('auth');
Route::post('anexos/{anexo}','AnexoController@approve')->middleware('auth')->name('anexos.approve');
Route::get('datos','AnexoController@datos')->middleware('verified')->name('datos');
Route::get('terminosCondiciones','AnexoController@terminosCondiciones')->middleware('verified')->name('terminosCondiciones');

//crud de usuarios
Route::resource('usuarios', 'UsuarioController')->middleware('verified');
Route::post('usuario/store','UsuarioController@store')->middleware('verified');
Route::post('usuario/update','UsuarioController@update')->middleware('verified');
Route::post('usuario/cambiarClave','UsuarioController@cambiarclave')->middleware('verified');
// Route::get('usuario/delete/{id?}','UsuarioController@destroy')->middleware('verified');
// Route::get('usuario/show/{id?}','UsuarioController@show')->middleware('verified');

//Rutas de Admin
Route::resource('clientes', 'ClienteController')->middleware('verified');
Route::post('anexoCliente/delete/{id?}','ClienteController@destroyAnexo')->middleware('auth')->name('borrarAnexoCliente');
Route::get('anexoCliente/show/{id?}', 'ClienteController@visualizar')->name('verAnexoCliente');

//Para buscar selects dinámicos
Route::get('/buscarDepartamento','DatosBasicosController@buscarDepartamento')->middleware('verified');
Route::get('/buscarMunicipio','DatosBasicosController@buscarMunicipio')->middleware('verified');
Route::get('/buscarUniversidad','EstudioFormalController@buscarUniversidad')->middleware('verified');

//Para asignar y quitar puntos puntos
Route::get('/asignarPuntos/{id}','PuntosController@asignarPuntos')->name('asignarPuntos')->middleware('verified');
Route::get('/quitarPuntos/{id}','PuntosController@quitarPuntos')->name('quitarPuntos')->middleware('verified');
Route::get('/puntosAcumulados','PuntosController@puntosAcumulados')->name('puntosAcumulados')->middleware('verified');

//Ruta para dashboard NO salen en primera versión
Route::get('inicioTester','InicioTesterController@index')->name('inicioTester')->middleware('verified');
Route::get('inicioLider','InicioLiderController@index')->name('inicioLider')->middleware('verified');
// Route::get('inicioAdmin','InicioAdminController@index')->name('inicioAdmin');
Route::get('puntosTester/{id}','PuntosController@mostrarPuntos')->name('puntosTester')->middleware('verified');

//Rutas para desactivar usuario
Route::get('/desactivar/{id}','DatosBasicosController@desactivar')->name('desactivar')->middleware('verified');

//Ruta para cambiar contraseña
Route::get('/editarContrasena/{id}','DatosBasicosController@editarContrasena')->name('editarContrasena')->middleware('verified');;
Route::put('/actualizarContrasena/{id}','DatosBasicosController@actualizarContrasena')->name('actualizarContrasena')->middleware('verified');;

//Ruta para anexos de tester

/*Route::get('/', function () {
    return view('home');
});*/
Route::get('/', 'HomeController@homeView');

//Ruta para devolver
Route::get('regresar', 'HomeController@return')->name('regresar');

//Rutas de paginas de inicio
Route::view('/about','about')->name('about');
Route::view('/contact','inicio_crowd.contacto')->name('contacto');
Route::post('contact', 'MessageController@store')->name('mensaje');

//crud de Anexos Proyectos
Route::resource('anexosProyectos','AnexosProyectosController')->middleware('verified');
Route::post('anexoProyectostore','AnexosProyectosController@store')->middleware('verified');
Route::get('anexoProyecto/{id?}','AnexosProyectosController@index')->middleware('verified');
Route::get('anexoProyecto/delete/{id?}','AnexosProyectosController@destroy')->middleware('verified');


//Rutas para el modulo de proyectos

Route::resource('misproyectos', 'MisproyectosController')->middleware('verified');
//correos inicio y fin
Route::get('mail/inicio/{id?}', 'InvitacionController@inicio')->middleware('verified');
Route::get('mail/fin/{id?}', 'InvitacionController@fin')->middleware('verified');

Route::resource('proyectos', 'ProyectosController')->middleware('verified');
Route::post('proyecto/store', 'ProyectosController@store')->middleware('verified');
Route::get('proyecto/delete/{id?}', 'ProyectosController@destroy')->middleware('verified');

Route::Resource('invitacion','InvitacionController')->middleware('verified');

Route::resource('invitaciones', 'InvitacionesController')->middleware('verified');
Route::get('invitaciones/edit/{id?}', 'InvitacionesController@edit')->middleware('verified');
Route::get('invitaciones/delete/{id?}', 'InvitacionesController@destroy')->middleware('verified');

Route::resource('proyectos_responsables', 'proyectos_responsablesController')->middleware('verified');
Route::post('proyectos_responsables/store', 'proyectos_responsablesController@store')->middleware('verified');
Route::get('proyectos_responsables/delete/{id?}', 'proyectos_responsablesController@destroy')->middleware('verified');
Route::get('proyectos_responsables/ver/{id?}', 'proyectos_responsablesController@ver')->middleware('verified');
Route::get('proyectos_responsables/edit/{id?}', 'proyectos_responsablesController@edit')->middleware('verified');

Route::get('proyectos_tester', 'proyectos_testerController@index')->middleware('verified');
Route::post('proyectos_tester/store', 'proyectos_testerController@store')->middleware('verified');
Route::get('proyectos_tester/delete/{id?}', 'proyectos_testerController@destroy')->middleware('verified');
Route::get('proyectos_tester/asignar/{id?}', 'proyectos_testerController@asignar')->middleware('verified');

//consultar si existen bugs en estado 1 o 6 para un tester o proyecto
Route::get('bugsxtester/{id?}','ValidarBugsController@tester')->middleware('verified');
Route::get('bugsxproyecto/{id?}','ValidarBugsController@proyecto')->middleware('verified');

Route::resource('alertas', 'AlertasController')->middleware('verified');
Route::post('alertas/asignarUsuarios', 'AlertasController@asignarUsuarios')->middleware('verified')->name('alertas.usuarios');

api/app/Models/Alerta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Alerta extends Model
{
    use SoftDeletes;
    protected $primaryKey='id_alerta';
    public $table = 'alertas';
    protected $fillable = ['titulo', 'mensaje','enlace','created_at','update_at'];

    public function alertasUsuario(){
        return $this->hasMany(AlertaUsuario::class, 'id_alerta');
    }

}

api/app/Http/Controllers/AlertasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Alerta;
use App\Models\AlertaUsuario;
use Chatify\Facades\ChatifyMessenger as Chatify;
use Flash;

class AlertasController extends Controller
{
    public function __construct()
    {
        $this->middleware([
            'auth', 'roles:1'
        ]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = \DB::table('users')->get();
        $alertas = Alerta::get();
        if (request()->ajax()) {
            return datatables()->of($alertas)
                ->addColumn('action_usuarios', 'alertas.buttons.actions_usuarios')
                ->addColumn('action', 'alertas.buttons.actions')
                ->editColumn('created_at', function($alerta){
                    return $alerta->created_at->format('d-m-Y');
                })
                ->editColumn('enlace', function ($alerta) {
                    return '<a href="'.$alerta->enlace.'">'.$alerta->enlace.'</a>';
                })
                ->rawColumns(['action_usuarios','action','enlace'])
                ->addIndexColumn()
                ->make(true);
        }
        return view('alertas.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        try {
            $data = $request->only('titulo', 'mensaje', 'enlace');
            Alerta::create($data);
            //\DB::table('alertas')->insert($data);
            Flash::success('Alerta creada correctamente');
            return redirect(route('alertas.index'));
            //code...
        } catch (\Throwable $th) {
            Flash::error('Hubo un error al crear la alerta');
            return redirect(route('alertas.index'));
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        return "hola store";
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        return "Vista sin funcion";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return "ola edit";
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        return "ola update";
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        return "ola destro";
    }

    public function asignarUsuarios(Request $request)
    {
        try {
            if (request()->ajax()) {
                $usuarios = AlertaUsuario::where('id_alerta',$request->id_alerta)->get();
                return \Response::json($usuarios);
            }
            $data = $request->only('alerta','usuarios');
            if(isset($data['usuarios'])){
                $usuarios = AlertaUsuario::where('id_alerta',$request->alerta)->get()->pluck('id_usuario')->toArray();
                $usuariosAdd = array_diff($data['usuarios'],$usuarios);
                $usuariosRem = array_diff($usuarios,$data['usuarios']);
                foreach ($usuariosAdd as $userID) {
                    AlertaUsuario::create([
                        'id_usuario' => $userID,
                        'id_alerta' => $data['alerta'],
                        'estado' => 'asignada'
                    ]);
                }
                foreach ($usuariosRem as $userID) {
                    AlertaUsuario::where([
                        'id_usuario' => $userID,
                        'id_alerta' => $data['alerta']
                    ])->delete();
                }
            }
            \Flash::success('Se guardaron los usuarios correctamente');
            return redirect(route('alertas.index'));
        } catch (\Throwable $th) {
            //throw $th;
            \Flash::error('Hubo un error al asignar los usuarios.');
            return redirect(route('alertas.index'));
        }
    }

    public function enviarAlerta(Request $request)
    {
        $alerta = Alerta::find($request->id_alerta);
        $usuarios = AlertaUsuario::where('id_alerta',$request->id_alerta)->get();
        foreach ($usuarios as $usuario) {
            // send to user using pusher
            AlertaUsuario::find($usuario->id_alertaUsuario)->update(['estado' => 'enviada']);
            Chatify::push('private-chatify', 'alert.'.$usuario->id_usuario, [
                'alerta' => $alerta,
                'usuario' => $usuario->id_usuario
            ]);
        }
        if($usuarios->isEmpty()){
            // Crear alerta general (Se crea al Admin)
            AlertaUsuario::create([
                'id_usuario' => '1',
                'id_alerta' => $alerta->id_alerta,
                'estado' => 'enviada'
            ]);
            // Se envia alerta a todos los usuarios
            Chatify::push('private-chatify', 'alert', [
                'alerta' => $alerta
            ]);
        }
    }

}

api/resources/views/alertas/index.blade.php
@extends('layouts.appBugs')

@section('content')
<div class="container" style="width:100%">
    <br>
    <a href="javascript:void(0)" class="btn btn-default btn-xs" id="create-new-alert">Crear alerta</a>
    <br><br>
    @include('flash::message')
    <table class="table table-bordered table-striped" id="alertas_datatable" style="width:100%; font-size:13px" data-turbolinks="false">
        <thead>
            <tr>
                <th style="min-width: 60px">ID alerta</th>
                <th style="min-width: 150px">Titulo</th>
                <th style="min-width: 150px">Mensaje</th>
                <th style="min-width: 80px">Enlace</th>
                <th style="min-width: 100px">Fecha de creación</th>
                <th style="min-width: 50px">Acciones</th>
            </tr>
        </thead>
    </table>
</div>
<script>
    $(document).ready(function() {
        $('#alertas_datatable thead tr:eq(1) th').each(function(i) {
            var title = $(this).text();
            $(this).html('<input type="text" style="font-size:12px; border-color:#304457; text-color:#ffff" placeholder="Buscar" />');

            $('input', this).on('keyup change', function() {
                if (table.column(i).search() !== this.value) {
                    table
                        .column(i)
                        .search(this.value)
                        .draw();
                }
            });
        });
    });
    var table = $('#alertas_datatable').DataTable({
        drawCallback: function(settings) {
            var api = this.api();
            var datos = api.rows({
                page: 'current'
            }).data();
            $.each(datos, function(i, item) {
                var btns = $('.dt-button');
                btns.addClass('btn btn-info btn-xs');
                btns.removeClass('dt-button');
            });
        },
        orderCellsTop: true,
        fixedHeader: false,
        processing: true,
        serverSide: true,
        scrollX: true,
        ajax: {
            url: "alertas",
            type: 'GET',
        },
        columns: [{
                data: 'id_alerta',
                name: 'id_alerta'
            },
            {
                data: 'titulo',
                name: 'titulo'
            },
            {
                data: 'mensaje',
                name: 'mensaje'
            },
            {
                data: 'enlace',
                name: 'enlace'
            },
            {
                data: 'created_at',
                name: 'created_at',
                type: "datetime"
            },
            {
                data: 'action',
                name: 'action'
            }
        ],
        order: [
            [0, 'desc']
        ],
        dom: 'Bfrtip',
        buttons: [
            [{
                extend: 'excel',
                exportOptions: {
                    orthogonal: 'export'
                }

            }],
            [{
                extend: 'pdfHtml5',
                orientation: 'landscape',
                pageSize: 'LEGAL',
                exportOptions: {
                    orthogonal: 'export'
                }
            }],
            [{
                extend: 'csv',
                exportOptions: {
                    orthogonal: 'export'
                }
            }],
            [{
                extend: 'print',
                text: 'Imprimir',
                exportOptions: {
                    orthogonal: 'export'
                }
            }],
        ],
    });
</script>
@include('alertas.modalCrearAlerta')
@include('alertas.modalAsignarUsuarios')
<script>
    $('#create-new-alert').click(function() {
        $('#alertForm').trigger("reset");
        $('#ajax-crud-modal').modal('show');
    });
    $(document).on('click', '.assign', function(e) {
        $('#listUsersAs li').appendTo('#listUsers');
        let obj = $(e.target).hasClass('lnr') ? $(e.target).parent() : $(e.target);
        const { id } = $(obj).data();
        $.ajax({
            type: "post",
            url: "{{ route('alertas.usuarios') }}",
            data: {
                id_alerta: id
            },
            success: function(response) {
                if (response.length > 0) {
                    response.forEach(alertaUser => {
                        $('#listUsers li[data-id="' + alertaUser.id_usuario + '"]').appendTo('#listUsersAs');
                    });
                }
                $('#alertUsersForm #alerta').val(id);
                $('#ajax-users-modal').modal('show');
            },
            error: function(data) {
                console.log('Error:', data);
                $('#btn-save').html('Guardar cambios');
            }
        });
    });
</script>
@endsection

api/resources/views/alertas/modalAsignarUsuarios.blade.php
<style>
    .listUsers {
        max-height: 300px;
        overflow: auto;
        padding-top: 10px;
        padding-left: 20px;
        list-style: none;
    }

    .listUsers li {
        cursor: pointer;
    }

    .listUsers li:hover {
        color: #3f8297;
        text-decoration: underline;
    }
</style>
<div class="modal fade" id="ajax-users-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="height:auto; padding-right:40px; padding-left:20px; padding-top:20px;">
            <div class="modal-header">
                <h4 class="modal-title" id="alertCrudModal">Asignar usuarios</h4>
            </div>
            <div class="modal-body d-flex" style="display: flex;flex-wrap: wrap;">
                <!-- Enlace -->
                <div class="row m-0" style="width: 100%;">
                    <div class="col-sm-6">
                        <label>Lista usuarios</label>
                        <div style="border:1px solid lightgray;min-height:100px">
                            <ul id="listUsers" class="listUsers">
                                @foreach($users as $user)
                                <li data-id="{{$user->id}}">
                                    {{ $user->name }} - {{ $user->email }}
                                    <input hidden type="text" name="usuarios[]" id="usuario{{$user->id}}" value="{{$user->id}}" />
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <label>Usuarios asignados</label>
                        <div style="border:1px solid lightgray;min-height:100px">
                            <form method="POST" action="{{ route('alertas.usuarios') }}" id="alertUsersForm" name="bugForm" class="form-horizontal" style="width: 100%;">
                                @csrf
                                <ul id="listUsersAs" class="listUsers"></ul>
                                <div style="display: none;">
                                    <input name="alerta" id="alerta" required>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 centrar" style="margin-top: 20px;">
                    <button type="button" class="btn btn-primary" id="btn-assign" value="assign-users">Guardar</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $(document).on('click', '#listUsers li', function(e) {
        $(this).appendTo('#listUsersAs');
    });
    $(document).on('click', '#listUsersAs li', function() {
        $(this).appendTo('#listUsers');
    });
    $('#btn-assign').on('click', function() {
        $('#alertUsersForm').submit();
    });
</script>

api/resources/views/alertas/modalCrearAlerta.blade.php
<div class="modal fade" id="ajax-crud-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="height:auto; width:600px; padding-right:40px; padding-left:20px; padding-top:20px;">
            <div class="modal-header">
                <h4 class="modal-title" id="alertCrudModal">Crear Alerta</h4>
            </div>
            <div class="modal-body d-flex" style="display: flex;flex-wrap: wrap;">
                <form action="{{ route('alertas.create') }}" id="alertForm" name="bugForm" class="form-horizontal">
                    <!-- Titulo -->
                    <div class="form-group col-sm-12" style="padding-bottom: 1px">
                        <label for="titulo">Titulo</label>
                        <input class="form-control" name="titulo" id="titulo" autocomplete="off" required>
                    </div>
                    <!-- Mensaje -->
                    <div class="form-group col-sm-12" style="padding-bottom: 1px">
                        <label for="mensaje">Mensaje</label>
                        <textarea class="form-control" name="mensaje" id="mensaje" required></textarea>
                    </div>
                    <!-- Enlace -->
                    <div class="form-group col-sm-12" style="padding-bottom: 1px">
                        <label for="enlace">Enlace</label>
                        <input class="form-control" name="enlace" id="enlace" required>
                    </div>
                    <div class="col-sm-12 centrar">
                        <button type="submit" class="btn btn-primary" id="btn-save" value="create-alert">Crear alerta</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>