api/routes/web.php
<?php

use Illuminate\Support\Facades\Storage;
use App\Mail\ReporteBugTester;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Log Viewer de produccion
Route::get('verLogCrowd','\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

//listado inicial con resumen de dispositivos
Route::get('info_dispositivos','infoDispositivosController@index')->name('info_dispositivos')->middleware('verified');
Route::get('sinDispositivos','infoDispositivosController@sinDispositivos')->name('sinDispositivos')->middleware('verified');
//Route::resource('infoPruebas', 'infoPruebasController')->middleware('verified');

//listado inicial con resumen de conocimiento en pruebas
Route::get('info_pruebas','infoPruebasController@index')->name('info_pruebas')->middleware('verified');
Route::get('sinPruebas','infoPruebasController@sinPruebas')->name('sinPruebas')->middleware('verified');

//crud de bugs
Route::resource('bugs','BugsController')->middleware('verified');
Route::post('bug/store','BugsController@store')->middleware('verified');
Route::get('bug/delete/{id?}','BugsController@destroy')->middleware('verified');
Route::get('bug/show/{id?}','BugsController@show')->middleware('verified');
Route::get('/buscarVersionSistemaOperativo','BugsController@buscarVersionSistemaOperativo')->middleware('verified');
Route::get('/buscarNavegador','BugsController@buscarNavegador')->middleware('verified');

//crud de Anexos Bugs
Route::resource('anexosBugs','AnexosBugsController')->middleware('verified');
Route::post('anexoBugstore','AnexosBugsController@store')->middleware('verified');
Route::get('anexoBug/{id?}','AnexosBugsController@index')->middleware('verified');
Route::get('anexoBug/delete/{id?}','AnexosBugsController@destroy')->middleware('verified');
Route::get('anexoBug/show/{id?}', 'AnexosBugsController@visualizar');

//crud de cuentas de cobro
Route::resource('cobros','CobrosController')->middleware('verified');
Route::get('cobro/show/{id?}','CobrosController@show')->middleware('verified');
Route::post('cobro/generar','CobrosController@generar')->middleware('verified');
Route::post('cobro/store','CobrosController@store')->middleware('verified');
Route::get('cobro/delete/{id?}','CobrosController@destroy')->middleware('verified');
//Para exportar como pdf
Route::get('imprimir/{id}','CobrosController@imprimir')->middleware('verified')->name('imprimir');
Route::post('usuarioCobro','CobrosController@usuarioCobro')->middleware('verified')->name('usuarioCobro');

Route::get('cobro/enviar','CobrosController@enviar')->middleware('verified')->name('cobros.enviar');
Route::post('cobro/enviar','CobrosController@enviarpdf')->middleware('verified')->name('cobros.enviarpdf');


//crud de Anexos Cuentas de cobro
Route::resource('anexosCobros','AnexosCobrosController')->middleware('verified');
Route::post('anexoCobrostore','AnexosCobrosController@store')->middleware('verified');
Route::get('anexoCobro/{id?}','AnexosCobrosController@index')->middleware('verified');
Route::get('anexoCobro/delete/{id?}','AnexosCobrosController@destroy')->middleware('verified');
Route::get('anexoCobro/show/{id?}', 'AnexosCobrosController@visualizar')->name('descargar');

//crud de dispositivos
Route::get('formulariosinfoDispositivos','formularioinfoDispositivosController@index')->name('formulariosinfoDispositivos')->middleware('verified');
Route::post('formulariosinfoDispositivosstore','formularioinfoDispositivosController@store')->middleware('verified');
Route::get('formulariosinfoDispositivosdelete/{id?}','formularioinfoDispositivosController@delete')->middleware('verified');

//crud de conocimiento en pruebas
Route::get('formulariosinfoPruebas','formularioinfoPruebasController@index')->name('formulariosinfoPruebas')->middleware('verified');
Route::post('formulariosinfoPruebasstore','formularioinfoPruebasController@store')->middleware('verified');
Route::get('formulariosinfoPruebasdelete/{id?}','formularioinfoPruebasController@delete')->middleware('verified');

//funciones para obtener listado de maestros: 
Route::get('/getherramientasxTipo/{id}', 'rutinasInfoPruebasController@getherramientasxTipo')->middleware('verified');
Route::get('/getDispositivosxTipo/{id}', 'rutinasInfoPruebasController@getDispositivosxTipo')->middleware('verified');
Route::get('/getDispositivos', 'rutinasInfoPruebasController@getDispositivos')->middleware('verified');
Route::get('/getMarcas', 'rutinasInfoPruebasController@getMarcas')->middleware('verified');
Route::get('/getModelos', 'rutinasInfoPruebasController@getModelos')->middleware('verified');
Route::get('/getSoxDispxTipo/{id}', 'rutinasInfoPruebasController@getSoxDispxTipo')->middleware('verified');
Route::get('/getNavDispxTipo/{id}', 'rutinasInfoPruebasController@getNavDispxTipo')->middleware('verified');

Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Rutas del módulo de Testers
Route::resource('datosBasicos', 'DatosBasicosController')->middleware('verified');
Route::resource('estudiosFormales', 'EstudioFormalController')->middleware('verified');
Route::resource('estudiosNoFormales', 'EstudioNoFormalController')->middleware('verified');
Route::resource('datosLaborales', 'DatoLaboralController')->middleware('verified');
Route::resource('datosFinancieros', 'DatosFinancierosController')->middleware('verified');
Route::resource('anexos','AnexoController')->middleware('auth');
Route::post('anexos/{anexo}','AnexoController@approve')->middleware('auth')->name('anexos.approve');
Route::get('datos','AnexoController@datos')->middleware('verified')->name('datos');
Route::get('terminosCondiciones','AnexoController@terminosCondiciones')->middleware('verified')->name('terminosCondiciones');

//crud de usuarios
Route::resource('usuarios', 'UsuarioController')->middleware('verified');
Route::post('usuario/store','UsuarioController@store')->middleware('verified');
Route::post('usuario/update','UsuarioController@update')->middleware('verified');
Route::post('usuario/cambiarClave','UsuarioController@cambiarclave')->middleware('verified');
// Route::get('usuario/delete/{id?}','UsuarioController@destroy')->middleware('verified');
// Route::get('usuario/show/{id?}','UsuarioController@show')->middleware('verified');

//Rutas de Admin
Route::resource('clientes', 'ClienteController')->middleware('verified');
Route::post('anexoCliente/delete/{id?}','ClienteController@destroyAnexo')->middleware('auth')->name('borrarAnexoCliente');
Route::get('anexoCliente/show/{id?}', 'ClienteController@visualizar')->name('verAnexoCliente');

//Para buscar selects dinámicos
Route::get('/buscarDepartamento','DatosBasicosController@buscarDepartamento')->middleware('verified');
Route::get('/buscarMunicipio','DatosBasicosController@buscarMunicipio')->middleware('verified');
Route::get('/buscarUniversidad','EstudioFormalController@buscarUniversidad')->middleware('verified');

//Para asignar y quitar puntos puntos
Route::get('/asignarPuntos/{id}','PuntosController@asignarPuntos')->name('asignarPuntos')->middleware('verified');
Route::get('/quitarPuntos/{id}','PuntosController@quitarPuntos')->name('quitarPuntos')->middleware('verified');
Route::get('/puntosAcumulados','PuntosController@puntosAcumulados')->name('puntosAcumulados')->middleware('verified');

//Ruta para dashboard NO salen en primera versión
Route::get('inicioTester','InicioTesterController@index')->name('inicioTester')->middleware('verified');
Route::get('inicioLider','InicioLiderController@index')->name('inicioLider')->middleware('verified');
// Route::get('inicioAdmin','InicioAdminController@index')->name('inicioAdmin');
Route::get('puntosTester/{id}','PuntosController@mostrarPuntos')->name('puntosTester')->middleware('verified');

//Rutas para desactivar usuario
Route::get('/desactivar/{id}','DatosBasicosController@desactivar')->name('desactivar')->middleware('verified');

//Ruta para cambiar contraseña
Route::get('/editarContrasena/{id}','DatosBasicosController@editarContrasena')->name('editarContrasena')->middleware('verified');;
Route::put('/actualizarContrasena/{id}','DatosBasicosController@actualizarContrasena')->name('actualizarContrasena')->middleware('verified');;

//Ruta para anexos de tester

/*Route::get('/', function () {
    return view('home');
});*/
Route::get('/', 'HomeController@homeView');

//Ruta para devolver
Route::get('regresar', 'HomeController@return')->name('regresar');

//Rutas de paginas de inicio
Route::view('/about','about')->name('about');
Route::view('/contact','inicio_crowd.contacto')->name('contacto');
Route::post('contact', 'MessageController@store')->name('mensaje');

//crud de Anexos Proyectos
Route::resource('anexosProyectos','AnexosProyectosController')->middleware('verified');
Route::post('anexoProyectostore','AnexosProyectosController@store')->middleware('verified');
Route::get('anexoProyecto/{id?}','AnexosProyectosController@index')->middleware('verified');
Route::get('anexoProyecto/delete/{id?}','AnexosProyectosController@destroy')->middleware('verified');


//Rutas para el modulo de proyectos

Route::resource('misproyectos', 'MisproyectosController')->middleware('verified');
//correos inicio y fin
Route::get('mail/inicio/{id?}', 'InvitacionController@inicio')->middleware('verified');
Route::get('mail/fin/{id?}', 'InvitacionController@fin')->middleware('verified');

Route::resource('proyectos', 'ProyectosController')->middleware('verified');
Route::post('proyecto/store', 'ProyectosController@store')->middleware('verified');
Route::get('proyecto/delete/{id?}', 'ProyectosController@destroy')->middleware('verified');

api/resources/views/layouts/appConocimiento.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Crowd</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no shrink-to-fit=no' name='viewport'>
 <!-- Bootstrap 3.3.7 

-->
    
  <link rel="stylesheet" href="{{ asset('/storage/css/bootstrap.css') }}">
  <link rel="stylesheet" href="{{ asset('/storage/css/iconos.css') }}">


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> 

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  {{-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"> --}}
  <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.1.2/handlebars.min.js"></script>
  {{-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> --}}
  {{-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> --}}

    <style>
      thead input {
         width: 100%;
      }

    .dropdown-toggle:focus {
      outline: 0;
      color: #304457;
    }
    .dropdown-menu {
      position: absolute;
      top: 100%;
      left: 0;
      z-index: 1000;
      display: none;
      float: left;
      min-width: 100PX;
      padding-left: 10px;
      /* padding: 5px 0;
      margin: 2px 0 0; */
      font-size: 14px;
      text-align: left;
      list-style: none;
      background-color: #304457!important;
      -webkit-background-clip: padding-box;
              background-clip: padding-box;
      border: 1px solid #304457;
      border: 1px solid rgba(0, 0, 0, .15);
      border-radius: 4px;
      -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, .175);
              box-shadow: 0 6px 12px rgba(0, 0, 0, .175);
    }
    .dropdown-menu.pull-right {
      right: 0;
      left: auto;
    }
    .dropdown-menu .divider {
      height: 1px;
      margin: 9px 0;
      overflow: hidden;
      background-color: #304457!important;
    }
    .dropdown-menu > li > a {
      display: block;
      padding: 3px 20px;
      clear: both;
      font-weight: normal;
      line-height: 1.42857143;
      color: #ffff!important;
      white-space: nowrap;
    }
    .dropdown-menu > li > a:hover,
    .dropdown-menu > li > a:focus {
      color: #f3a100!important;
      text-decoration: none;
      background-color: transparent;
    }
    .dropdown-menu > .active > a,
    .dropdown-menu > .active > a:hover,
    .dropdown-menu > .active > a:focus {
      color: #fff!important;
      text-decoration: none;
      background-color: #f3a100!important;
      outline: 0;
    }
    .dropdown-menu > .disabled > a,
    .dropdown-menu > .disabled > a:hover,
    .dropdown-menu > .disabled > a:focus {
      color: #304457!important;
    }

    .open > .dropdown-menu {
      display: block;
      border-top: 2px solid #f3a100!important;
    }

    .dropdown-header {
      display: block;
      padding: 3px 20px;
      font-size: 12px;
      line-height: 1.42857143;
      color: #304457 !important;
      white-space: nowrap;
    }

    .navbar-default .navbar-collapse,
    .navbar-default .navbar-form {
      border-color: #304457!important;
    }
    .navbar-default .navbar-nav > .open > a,
    .navbar-default .navbar-nav > .open > a:hover,
    .navbar-default .navbar-nav > .open > a:focus {
      color: #F3A100!important;
      background-color: #304457!important;
    }

    .navbar-default .navbar-nav>li>a {
    color: #fff!important;
    }

    .dropdown-menu > li > a:hover,
    .dropdown-menu > li > a:focus {
      color: #f3a100!important;
      text-decoration: none;
      background-color: transparent!important;
    }

}

  </style>
   <style>
      .modal-sm {
         width: 80%; /* New width for large modal */
         height: 500px;
         background-color:#BBD6EC;
      }

      .navbar-default {
          background-color: #304457!important;
          border-color: #304457!important;
      }

          .navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus {
          color: #f3A100!important;
          background-color: transparent!important;
        }

      
  </style>
  <script type="text/javascript">
      function go(miframe, url) {
          document.getElementById(miframe).src = url;
      }
  </script>
    
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    <a class="navbar-brand" href="{{ url('/') }}">
      <img src="/storage/images/logo.png"  width="35%"/>
      
    </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">


                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="/storage/avatars/{{auth()->user()->avatar}}"  width="30px" class="img-circle" alt="Avatar"> <span>{{auth()->user()->name}}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                  <ul class="dropdown-menu">
                    @if(auth()->user()->hasRoles(['2']))
                      <li><a href="{{ route('datosBasicos.index') }}"><i class="lnr lnr-user"></i> <span>Mi Perfil</span></a></li>
                      <li><a href="{{ route('invitaciones.index') }}"><i class="lnr lnr-flag"></i> <span>Mis invitaciones</span></a></li>
                      <li><a href="{{ route('misproyectos.index') }}"><i class="lnr lnr-cog"></i> <span>Mis proyectos</span></a></li>
                      <li><a href="{{ route('bugs.index') }}"><i class="lnr lnr-bug"></i> <span>Mis hallazgos</span></a></li>
                      <li><a href="{{ route('cobros.index') }}"><i class="lnr lnr-chart-bars"></i> <span>Mis cuentas de Cobro</span></a></li>   
                      <li><a href="{{ route('puntosTester',auth()->user()->id) }}"><i class="lnr lnr-thumbs-up" ></i> <span>Mis puntos </span></a></li>
                      @endif
                      @if(auth()->user()->hasRoles(['3']))
                      <li><a href="{{ route('datosBasicos.index') }}"><i class="lnr lnr-user"></i> <span>Mi Perfil</span></a></li>
                      <li><a href="{{ route('clientes.index') }}"><i class="lnr lnr-sync"></i> <span>Clientes</span></a></li>
                      <li><a href="{{ route('proyectos.index') }}"><i class="lnr lnr-cog"></i> <span>Proyectos</span></a></li>
                      <li><a href="{{ route('bugs.index') }}"><i class="lnr lnr-bug"></i> <span>Hallazgos</span></a></li>
                      <li><a href="{{ route('cobros.index') }}"><i class="lnr lnr-chart-bars"></i> <span>Cuentas de Cobro</span></a></li>
                      @endif
                      @if(auth()->user()->hasRoles(['1']))
                      <li><a href="{{ route('datosBasicos.index') }}"><i class="lnr lnr-user"></i> <span>Mi Perfil</span></a></li>
                      <li><a href="{{ route('usuarios.index') }}"><i class="lnr lnr-users"></i> <span>Usuarios</span></a></li>
                      <li><a href="{{ route('clientes.index') }}"><i class="lnr lnr-sync"></i> <span>Clientes</span></a></li>
                      <li><a href="{{ route('proyectos.index') }}"><i class="lnr lnr-cog"></i> <span>Proyectos</span></a></li>
                      <li><a href="{{ route('bugs.index') }}"><i class="lnr lnr-bug"></i> <span>Hallazgos</span></a></li>
                      <li><a href="{{ route('cobros.index') }}"><i class="lnr lnr-chart-bars"></i> <span>Cuentas de Cobro</span></a></li>
                      <li><a href="{{ route('puntosTester',auth()->user()->id) }}"><i class="lnr lnr-thumbs-up" ></i> <span>Mis puntos </span></a></li>
                      @endif
                      @if(auth()->user()->hasRoles(['4']))
                      <li><a href="{{ route('cobros.index') }}"><i class="lnr lnr-chart-bars"></i> <span>Cuentas de Cobro</span></a></li>
                      @endif
                      <li> <a href="{!! url('/logout') !!}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="lnr lnr-exit"></i> <span>Cerrar sesión</span></a>
                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                        </form> 
                      </li>
                  </ul>
                </li>
                   
          </ul>
          </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="main">

  <form method="POST" id="signup-form" class="signup-form" enctype="multipart/form-data">
      <h3>
        <a class= "title-text" href="{{ route('datosBasicos.index') }}">Datos Básicos</a>
      </h3>
      <fieldset>
      </fieldset>

      <h3>
        <a class= "title-text" href="{{ route('estudiosFormales.index') }}">Estudios Formales</a>
      </h3>
      <fieldset>
      </fieldset>

      <h3>
        <a class= "title-text" href="{{ route('estudiosNoFormales.index') }}">Estudios no Formales</a>
      </h3>
      <fieldset> 
      </fieldset>

      <h3>
        <a class= "title-text" href="{{ route('datosLaborales.index') }}">Información Laboral</a>
      </h3>
    <fieldset> 
    </fieldset>

     <h3>
      @if(Route::current()->getName() == 'info_pruebas')
      <a class= "title-text" href="{{ ('sinPruebas') }}" style="color:#304457">Conocimiento en Pruebas</a>
      @else
      <a class= "title-text" href="{{ ('sinPruebas') }}">Conocimiento en Pruebas</a>
      @endif
   </h3>
    <fieldset> 
    </fieldset>

    <h3>
      @if(Route::current()->getName() == 'info_dispositivos')
      <a class= "title-text" href="{{ ('sinDispositivos') }}" style="color:#304457">Mis dispositivos</a>
      @else
      <a class= "title-text" href="{{ ('sinDispositivos') }}">Mis dispositivos</a>
      @endif
   </h3>
   <fieldset> 
   </fieldset>

     <h3>
      <a class= "title-text" href="{{ route('datosFinancieros.index') }}">Información Financiera</a>
    </h3>
    <fieldset> 
    </fieldset>

    <h3>
      <a class= "title-text" href="{{ route('anexos.index') }}">Anexos</a>
   </h3>
   <fieldset> 
   </fieldset>

   
    </form>

    @yield('content')

    

</div>


    <!-- jQuery 3.1.1 -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    

    <script src="{{ asset("storage/vendor/jquery-steps/jquery.steps.min.js") }}"></script>
    <script src="{{ asset("storage/js/main.js") }}"></script>



  @yield('scripts')

  <script>

    var pageURL = $(location).attr("href");

    var elements = document.getElementsByClassName("title-text")
    for (var i = 0; i < elements.length; i++) {
   
      //if you want to change bg image
      //if you want to change bg color
      
      if (( elements[i].href)==pageURL)
      {

     // elements[i].style.backgroundColor="" ;
      elements[i].style.color="#304457" ;
      }
    }
  </script>
  

</body>



</html>

api/resources/views/layouts/appPDF.blade.php
<!-- Este layout es para plantillas de correo -->

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ asset('/storage/css/bootstrap.css') }}">
</head>

<body>
@yield('content')  
</body>

</html>

api/resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

api/resources/views/layouts/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	Por favor busca los errores más abajo
</div>
@endif

api/resources/views/layouts/nav.blade.php
{{-- <style>
  #mainNav {
      padding-top: 0;
      padding-bottom: 0;
      border-bottom: none;
      background-color: transparent!important;
      transition: background-color .3s ease-in-out;
  }
  #mainNav {
      min-height: 57px;
      background-color: #b6ecfd!important;
  }

</style> --}}

<nav class="navbar navbar-light navbar-expand-lg shadow-sm fixed-top" style="color:#304457" id="mainNav">

  <a href="{{ url('/') }}" style="text-decoration: none;">
    <img src="/img/logo_crowd_leyenda.png"  width="50%"/></a>
    <br>
  

<!--
    <button class="navbar-toggler" type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="{{ __('Toggle navigation') }}">
      <span class="navbar-toggler-icon"></span>
    </button>
-->
    <div class="container"> 
      <div class="collapse navbar-collapse border-0" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
        <!--
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="scrollbar-shadow-color: #f3a100" href="#about">Sobre nosotros</a>
          </li>
          -->

          @auth
            @if(auth()->user()->hasRoles(['1','2','3']))
            <a class="nav-link" href="{{ route('datosBasicos.index') }}" style="font-family: HelveticaNeueLTStd-Hv;font-size: 1.3vw">Mi perfil</a>
            @endif
            @if(auth()->user()->hasRoles(['4']))
            <a class="nav-link" href="{{ route('cobros.index') }}" style="font-family: HelveticaNeueLTStd-Hv;font-size: 1.3vw">Mi perfil</a>
            @endif
          @else
            <li class="nav-item">
              <a class="nav-link" href="{{ route('register') }}" style="font-family: HelveticaNeueLTStd-Hv;font-size: 1.3vw">Registrarme</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('login') }}" style="font-family: HelveticaNeueLTStd-Hv;font-size: 1.3vw">Ingresar</a>
            </li>
          @endauth
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{ route('contacto') }}" style="font-family: HelveticaNeueLTStd-Hv;font-size: 1.3vw">Contáctanos</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
   <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
</form>

@yield('content')